//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class DB_14781_testdbEntities : DbContext
{
    public DB_14781_testdbEntities()
        : base("name=DB_14781_testdbEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<school_events> school_events { get; set; }
    public DbSet<school_news> school_news { get; set; }
    public DbSet<health_career> health_career { get; set; }
    public DbSet<health_services> health_services { get; set; }
    public DbSet<health_news> health_news { get; set; }
    public DbSet<health_rooms> health_rooms { get; set; }
}
