//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class health_career
{
    public int id { get; set; }
    public string name { get; set; }
    public string descrip { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public string link { get; set; }
    public string contact { get; set; }
    public string email { get; set; }
    public string phone { get; set; }
    public string image { get; set; }
    public string htmlContent { get; set; }
    public Nullable<int> archived { get; set; }
}

public partial class health_news
{
    public int id { get; set; }
    public string name { get; set; }
    public string descrip { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public string link { get; set; }
    public string contact { get; set; }
    public string email { get; set; }
    public string phone { get; set; }
    public string image { get; set; }
    public string htmlContent { get; set; }
    public Nullable<int> archived { get; set; }
}

public partial class health_rooms
{
    public int id { get; set; }
    public string name { get; set; }
    public string descrip { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public string link { get; set; }
    public string contact { get; set; }
    public string email { get; set; }
    public string phone { get; set; }
    public string image { get; set; }
    public string htmlContent { get; set; }
    public Nullable<int> archived { get; set; }
}

public partial class health_services
{
    public int id { get; set; }
    public string name { get; set; }
    public string descrip { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public string link { get; set; }
    public string contact { get; set; }
    public string email { get; set; }
    public string phone { get; set; }
    public string image { get; set; }
    public string htmlContent { get; set; }
    public Nullable<int> archived { get; set; }
}

public partial class school_events
{
    public int id { get; set; }
    public string name { get; set; }
    public string name_sub { get; set; }
    public string name_heading { get; set; }
    public string descrip { get; set; }
    public string descrip2 { get; set; }
    public string htmlContent { get; set; }
    public Nullable<System.DateTime> eventDate { get; set; }
    public string contact { get; set; }
    public string contactEmail { get; set; }
    public string phone { get; set; }
    public Nullable<int> archived { get; set; }
    public string eventImage { get; set; }
    public string admission { get; set; }
}

public partial class school_news
{
    public int id { get; set; }
    public string name { get; set; }
    public string descrip { get; set; }
    public Nullable<System.DateTime> date { get; set; }
    public string link { get; set; }
    public string contact { get; set; }
    public string email { get; set; }
    public string phone { get; set; }
    public string image { get; set; }
    public string htmlContent { get; set; }
    public Nullable<int> archived { get; set; }
}
